"""Create a new documentation repository from the versioned-md template."""

import logging
import sys
from pathlib import Path

import yaml
from jinja2 import Environment, FileSystemLoader

import versioned_md

log = logging.getLogger(__name__)


CONFIG_TEMPLATE = """# versioned-md configuration for this repository
# This file is generated by `versioned-md create` and controls template updates.

template:
  name: "{name}"
  description: "{description}"
  org: "{org}"
  author: "{author}"
"""


def _normalize_name(name: str) -> str:
    """Convert a repo name to a safe directory name."""
    return name.strip().lower().replace(" ", "-").replace("_", "-")


def _write_config(outdir: Path, context: dict) -> None:
    """Write .versioned-md.yml config file."""
    content = CONFIG_TEMPLATE.format(
        name=context["name"],
        description=context["description"],
        org=context["org"],
        author=context["author"],
    )
    (outdir / ".versioned-md.yml").write_text(content, encoding="utf-8")


def _is_binary_file(p: Path) -> bool:
    """Check if a file is binary."""
    try:
        p.read_text(encoding="utf-8")
        return False
    except (UnicodeDecodeError, ValueError):
        return True


def render_template(template_dir: Path, outdir: Path, context: dict, force: bool) -> None:
    """Render the embedded template into outdir.

    Args:
        template_dir: Path to versioned_md/templates/
        outdir: Path where the new repo will be created
        context: Dict of Jinja2 variables
        force: Whether to overwrite existing files
    """
    outdir.mkdir(parents=True, exist_ok=True)

    # Build Jinja2 environment
    env = Environment(loader=FileSystemLoader(str(template_dir)), keep_trailing_newline=True)

    template_files = list(template_dir.rglob("*"))

    for template_file in template_files:
        if template_file.is_dir():
            continue

        rel_path = template_file.relative_to(template_dir)
        out_path = outdir / rel_path

        # Skip Python caches and temp files
        if any(s in str(template_file) for s in [".pyc", "__pycache__", ".pyo", ".pyd"]):
            continue

        # Skip files that should only exist in nf-core org repos
        org = context.get("org", "")
        if org != "nf-core" and "nf-core" in str(rel_path).lower():
            continue

        # Create parent directories
        out_path.parent.mkdir(parents=True, exist_ok=True)

        try:
            # Check if binary
            if _is_binary_file(template_file):
                if out_path.exists() and not force:
                    continue
                import shutil

                shutil.copy2(template_file, out_path)
                continue

            # Render with Jinja2
            j_template = env.get_template(str(rel_path))
            rendered = j_template.render(context)

            # Check if would overwrite and force is not set
            if out_path.exists() and not force:
                log.error(f"File already exists: {out_path}")
                raise ValueError(f"File already exists: {out_path}")

            out_path.write_text(rendered, encoding="utf-8")

        except Exception as exc:
            if "already exists" in str(exc) and not force:
                raise
            log.debug(f"Could not render {rel_path}: {exc}, copying as-is")
            import shutil

            try:
                shutil.copy2(template_file, out_path)
            except Exception:
                pass


def _git_init(outdir: Path) -> bool:
    """Initialise git repo and create main + TEMPLATE branches."""
    import git

    try:
        repo = git.Repo.init(outdir)
        repo.git.checkout(["-b", "main"])
        repo.git.add(A=True)
        repo.index.commit("[versioned-md] initial documentation repository")

        # Create the TEMPLATE branch (same content as main)
        repo.git.checkout("main")
        repo.git.checkout(["-b", "TEMPLATE"])

        # Go back to main
        repo.git.checkout("main")

        log.info("Created branches: main, TEMPLATE")
        return True

    except git.GitCommandError as e:
        log.error(f"Failed to initialise git: {e}")
        return False


class CreateApplication:
    """Application object for 'versioned-md create'."""

    def __init__(
        self,
        name: str = "",
        description: str = "",
        author: str = "",
        org: str = "",
        outdir: str = ".",
        config_file: str | None = None,
        force: bool = False,
        no_git: bool = False,
    ):
        self.name = name
        self.description = description
        self.author = author
        self.org = org
        self.outdir = outdir or "."
        self.config_file = config_file
        self.force = force
        self.no_git = no_git

    def run(self, is_interactive: bool = False) -> int:
        """Run the create application. Returns exit code."""
        # Gather context
        ctx = {
            "name": self.name,
            "description": self.description,
            "org": self.org,
            "author": self.author,
        }

        if is_interactive:
            ctx["name"] = self.name or self._prompt("Repository name")
            ctx["description"] = self.description or self._prompt("Description", "Documentation repository")
            ctx["author"] = self.author or self._prompt("Author / Organisation")
            ctx["org"] = self.org or self._prompt("Organisation / GitHub username")

        context = self._load_config(ctx)

        outdir = Path(self.outdir) / context["repo_name"]
        if not outdir.exists() or self.force:
            outdir.mkdir(parents=True, exist_ok=True)
        else:
            log.error(f"Output directory already exists: {outdir}")
            log.info("Use --force to overwrite.")
            return 1

        # Render template
        template_dir = Path(versioned_md.__file__).parent / "templates"
        log.info(f"Rendering template from {template_dir}")
        render_template(template_dir, outdir, context, self.force)

        # Write config
        _write_config(outdir, context)

        # Git init
        if not self.no_git:
            log.info(f"Initialising git repository in {outdir}")
            if not _git_init(outdir):
                return 1

            log.info("Done. Add a remote and push:")
            log.info(f"  cd {outdir}")
            log.info(f"  git remote add origin git@github.com:USERNAME/{context['repo_name']}.git")
            log.info("  git push --all origin")
        else:
            log.info(f"Repo created at {outdir} (no git)")

        log.info("Done.")
        return 0

    def _load_config(self, ctx: dict) -> dict:
        """Load config from file if provided, filling in missing values."""
        if not self.config_file:
            # Compute derived values for non-config case
            name = ctx["name"]
            if not name:
                log.error("No repository name provided")
                sys.exit(1)
            ctx["repo_name"] = _normalize_name(name)
            ctx["short_name"] = _normalize_name(name)
            ctx["name_noslash"] = ctx["repo_name"]
            ctx["is_nfcore"] = ctx["org"] == "nf-core"
            if not ctx["description"]:
                ctx["description"] = f"Documentation for {name}"
            if not ctx["org"]:
                ctx["org"] = ctx["author"] or "unknown"
            if not ctx["author"]:
                ctx["author"] = ctx["org"]
            return ctx

        config_path = Path(self.config_file)
        try:
            config_data = yaml.safe_load(config_path.read_text(encoding="utf-8"))
            template_config = config_data.get("template", {})
        except Exception as exc:
            log.error(f"Failed to load config: {exc}")
            sys.exit(1)

        result = {
            "name": ctx["name"] or template_config.get("name", ""),
            "description": ctx["description"] or template_config.get("description", ""),
            "org": ctx["org"] or template_config.get("org", ""),
            "author": ctx["author"] or template_config.get("author", ""),
        }

        if not result["name"]:
            log.error("No repository name provided")
            sys.exit(1)
        if not result["description"]:
            result["description"] = f"Documentation for {result['name']}"
        if not result["org"]:
            result["org"] = ctx["author"] or "unknown"
        if not result["author"]:
            result["author"] = result["org"]

        result["repo_name"] = _normalize_name(result["name"])
        result["short_name"] = _normalize_name(result["name"])
        result["name_noslash"] = result["repo_name"]
        result["is_nfcore"] = result["org"] == "nf-core"

        return result

    def _prompt(self, message: str, default: str = "") -> str:
        """Interactive prompt helper."""
        if default:
            prompt = f"{message} [{default}]: "
        else:
            prompt = f"{message}: "
        value = input(prompt).strip()
        return value or default


class InitApplication:
    """Application object for 'versioned-md init'."""

    def __init__(
        self,
        path: Path,
        person_name: str = "",
        person_handle: str = "",
        person_initials: str = "",
        force: bool = False,
        run_interactive: bool = False,
    ):
        self.path = Path(path)
        self.person_name = person_name
        self.person_handle = person_handle
        self.person_initials = person_initials
        self.force = force
        self.run_interactive = run_interactive

    def run(self) -> int:
        """Initialise the repo with TEMPLATE branch and people.json."""
        import git

        try:
            repo = git.Repo(self.path)
        except git.InvalidGitRepositoryError:
            log.error(f"{self.path} is not a git repository")
            return 1

        has_main = "main" in repo.branches or "main" in repo.refs
        has_template = "TEMPLATE" in repo.branches or "TEMPLATE" in repo.refs

        if has_main and has_template:
            if not self.force:
                log.info("Template branches (main, TEMPLATE) already exist. Use --force to recreate.")
                return 0
            for branch_name in ["main", "TEMPLATE"]:
                try:
                    branch = repo.branches[branch_name]
                    branch.delete(force=True)
                except KeyError:
                    pass

        current_head = repo.head.commit

        if not has_main:
            repo.git.checkout(["-b", "main"])
        elif has_main and has_template:
            ref = repo.heads.main
            ref.reset(current_head, hard=True)

        if not has_template:
            repo.git.checkout(["-b", "TEMPLATE"])
        elif has_template:
            repo.git.checkout("TEMPLATE")
            ref = repo.heads.TEMPLATE
            ref.reset(current_head, hard=True)

        try:
            repo.git.checkout("main")
        except git.InvalidGitRepositoryError:
            repo.git.checkout(["-b", "main"])

        log.info("Template branches initialised.")

        # Gather person data
        import os
        import sys

        has_args = bool(self.person_name or self.person_handle or self.person_initials)
        is_tty = os.isatty(sys.stdin.fileno()) and os.isatty(sys.stdout.fileno())

        if self.run_interactive and not has_args:
            self.person_name = self._prompt("Person name")
            self.person_handle = self._prompt("Handle (e.g. github username)")
            self.person_initials = self._prompt("Initials (e.g. JD)")

        if has_args and not self.run_interactive:
            pass
        elif not has_args and not is_tty:
            log.error("Not running interactively. Provide --person-name, --person-handle, and --person-initials.")
            return 1
        elif not has_args and is_tty:
            self.person_name = self._prompt("Person name")
            self.person_handle = self._prompt("Handle (e.g. github username)")
            self.person_initials = self._prompt("Initials (e.g. JD)")

        if not self.person_name or not self.person_handle or not self.person_initials:
            log.error("All person fields (name, handle, initials) are required.")
            return 1

        # Write people.json
        from versioned_md.people import write_people_file

        return write_people_file(self.path, self.person_name, self.person_handle, self.person_initials)

    def _prompt(self, message: str, default: str = "") -> str:
        """Interactive prompt helper."""
        if default:
            prompt_str = f"{message} [{default}]: "
        else:
            prompt_str = f"{message}: "
        value = input(prompt_str).strip()
        return value or default
